<h1>Array Attributes


In [2]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
a3

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [3]:
#ndim--->> number of dimensions 

a1.ndim
a2.ndim
a3.ndim

3

In [4]:
#shape
 ## har dimension m kitne items h ##

a1.shape
a2.shape
a3.shape

#(2,2,2)  iska mtlb h ki kitne 2d arrays h and unka kitna row kitna column h 

(2, 2, 2)

In [5]:
#size -->> no. of items

print(a2.size)

12


In [6]:
#itemsize   -->> memory m kitte bytes h each item k 
a3.itemsize

print(a2.itemsize)
#int 32 4 byte leta h and int 64 8 byte leta h 

8


In [7]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing datatype

In [8]:
#astype   --->> file size manuplation usedd fro memory optimisation
a3.astype(np.int32) 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array ops


In [9]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
#scalar operations 


#arithmetic -->> sara ka sara apply hoga you can do that 

print(a1+a2)

print(a1-a2)

print(a1*a2)

print(a1/a2)


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [11]:
#relational 
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [12]:
#vector ops 
#arithmetic


print(a1+a2)

a1**a2

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [13]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1 

array([[62., 65., 68.],
       [67., 83., 11.],
       [33., 38., 19.]])

In [14]:
#max / min / sum / prod


np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)

np.float64(399402405813840.0)

In [15]:
# 0->>column  and 1-->>row 

#column-wise
np.max(a1,axis=0)

#row-wise
np.max(a1,axis=1)


#all other functions are applicable 

array([68., 83., 38.])

mean / median / std /var

In [16]:
np.mean(a1,axis=0)

array([54.        , 62.        , 32.66666667])

In [17]:
np.median(a1,axis=0)

array([62., 65., 19.])

In [18]:
np.var(a1,axis=1)

array([  6.        , 952.88888889,  64.66666667])

In [19]:
#trigonometric
np.sin(a1)  

#all trigo formula valid

array([[-0.7391807 ,  0.82682868, -0.89792768],
       [-0.85551998,  0.96836446, -0.99999021],
       [ 0.99991186,  0.29636858,  0.14987721]])

DOt product


In [20]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [21]:
#log and exponents
np.log(a1)

array([[4.12713439, 4.17438727, 4.21950771],
       [4.20469262, 4.41884061, 2.39789527],
       [3.49650756, 3.63758616, 2.94443898]])

In [22]:
np.exp(a1)

array([[8.43835667e+26, 1.69488924e+28, 3.40427605e+29],
       [1.25236317e+29, 1.11286375e+36, 5.98741417e+04],
       [2.14643580e+14, 3.18559318e+16, 1.78482301e+08]])

In [23]:
#round / ceil  /floor 

np.round(np.random.random((2,3))*100)

# floor -->> piche wale element pr phenkta h 
np.floor(np.random.random((2,3))*100)

#ceil -->> aage wale element pr phenkta h 
np.ceil(np.random.random((2,3))*100)

array([[100.,  43.,  79.],
       [ 29.,  84.,  62.]])

Indexing /slicing 

In [24]:
a1= np.arange(10)
a2= np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)



In [25]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a1[0]

np.int64(0)

In [27]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a2[1,2]  #extracting 6 

a2[2,3] #11

np.int64(11)

In [29]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
a3[0,1,0]  #extracting 2 

a3[1,0,1]  # 5 

#1st konsa matrix , row , column

np.int64(5)

In [31]:
#slicing 

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a1[2:5]  # same as py

array([2, 3, 4])

In [33]:
a1[2:5:2]  # 2 2 k gap me 

array([2, 4])

In [34]:
#2d
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a2[0,:] #extracting 1st row 

# 1st input index of row and for all columns use (:)

array([0, 1, 2, 3])

In [36]:
a2[:,2]    #column extraction

array([ 2,  6, 10])

In [37]:
a2[1:,1:3]  # row kha se kha tk , column kha se kha tk

array([[ 5,  6],
       [ 9, 10]])

In [38]:
a2[::2,::3]    # 0 8 
  # tino rows toh ::2 --->> rows alternate
  # tino columns toh ::3 --->> columns alternate 

array([[ 0,  3],
       [ 8, 11]])

In [40]:
a2[::2,1::2] 

array([[ 1,  3],
       [ 9, 11]])

In [41]:
a2[1,::3]

array([4, 7])

In [45]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [48]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1] #bich wala 
a3[0::2]  #1st n last 


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,1,:]  #jb sari rows and columns chiye toh : use kro 

array([12, 13, 14])

In [61]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1: ,1:]

#1: means 1 onwards--> 1 k age k age se sb kuch 
#  and :1 means --> start up but not including index 1 

array([24, 25, 26])

In [64]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating 

In [65]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [67]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
for i in a2:
    print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [71]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [72]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):   #pura kholdega 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


RESHAPING

In [ ]:
#reshape allready done 

In [75]:
#transpose 

print(a2)

np.transpose(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [76]:
#simpller
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [81]:
#ravel -->> n dimension to 1d array 

a2.ravel
print(a3.ravel)

<built-in method ravel of numpy.ndarray object at 0x0000028C7E659770>


STACKING

In [93]:
#horizontal stacking 

a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [ ]:
np.hstack((a4,a5))

In [ ]:
#vertical stacking 
np.vstack((a4,a5)) 

#in stacking dono ka shape same honA CHIYE

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

SPLITTING

In [ ]:
#horizontal
a4

np.hsplit(a4,4)  #2 is kitne tukde krne h equal
# division must be equal

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [97]:
#vertical splitting 

np.vsplit(a5,3)

#print(a5)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]