<h1>Array Attributes


In [4]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
a3

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
#ndim--->> number of dimensions 

a1.ndim
a2.ndim
a3.ndim

3

In [ ]:
#shape
 ## har dimension m kitne items h ##

a1.shape
a2.shape
a3.shape

#(2,2,2)  iska mtlb h ki kitne 2d arrays h and unka kitna row kitna column h 

(2, 2, 2)

In [13]:
#size -->> no. of items

print(a2.size)

12


In [ ]:
#itemsize   -->> memory m kitte bytes h each item k 
a3.itemsize

print(a2.itemsize)
#int 32 4 byte leta h and int 64 8 byte leta h 

8


8

In [18]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing datatype

In [ ]:
#astype   --->> file size manuplation usedd fro memory optimisation
a3.astype(np.int32) 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array ops


In [22]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
#scalar operations 


#arithmetic -->> sara ka sara apply hoga you can do that 

print(a1+a2)

print(a1-a2)

print(a1*a2)

print(a1/a2)


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [25]:
#relational 
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
#vector ops 
#arithmetic


print(a1+a2)

a1**a2

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [30]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1 

array([[11., 87.,  3.],
       [22., 99., 60.],
       [33., 70., 85.]])

In [36]:
#max / min / sum / prod


np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)

np.float64(73667040678000.0)

In [ ]:
# 0->>column  and 1-->>row 

#column-wise
np.max(a1,axis=0)

#row-wise
np.max(a1,axis=1)


#all other functions are applicable 

array([87., 99., 85.])

mean / median / std /var

In [41]:
np.mean(a1,axis=0)

array([22.        , 85.33333333, 49.33333333])

In [42]:
np.median(a1,axis=0)

array([22., 87., 60.])

In [43]:
np.var(a1,axis=1)

array([1432.88888889,  988.22222222,  477.55555556])

In [ ]:
#trigonometric
np.sin(a1)  

#all trigo formula valid

array([[-0.99999021, -0.82181784,  0.14112001],
       [-0.00885131, -0.99920683, -0.30481062],
       [ 0.99991186,  0.77389068, -0.17607562]])

DOt product


In [46]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [47]:
#log and exponents
np.log(a1)

array([[2.39789527, 4.46590812, 1.09861229],
       [3.09104245, 4.59511985, 4.09434456],
       [3.49650756, 4.24849524, 4.44265126]])

In [48]:
np.exp(a1)

array([[5.98741417e+04, 6.07603023e+37, 2.00855369e+01],
       [3.58491285e+09, 9.88903032e+42, 1.14200739e+26],
       [2.14643580e+14, 2.51543867e+30, 8.22301271e+36]])

In [53]:
#round / ceil  /floor 

np.round(np.random.random((2,3))*100)

# floor -->> piche wale element pr phenkta h 
np.floor(np.random.random((2,3))*100)

#ceil -->> aage wale element pr phenkta h 
np.ceil(np.random.random((2,3))*100)

array([[ 53.,  47.,  78.],
       [100.,  12.,   8.]])

Indexing /slicing 

In [59]:
a1= np.arange(10)
a2= np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)



In [60]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a1[0]

np.int64(0)

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a2[1,2]  #extracting 6 

a2[2,3] #11

np.int64(11)

In [65]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[0,1,0]  #extracting 2 

a3[1,0,1]  # 5 

#1st konsa matrix , row , column

np.int64(5)

In [69]:
#slicing 

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]  # same as py

array([2, 3, 4])

In [ ]:
a1[2:5:2]  # 2 2 k gap me 

array([2, 4])

In [74]:
#2d
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:] #extracting 1st row 

# 1st input index of row and for all columns use (:)

array([0, 1, 2, 3])

In [ ]:
a2[:,2]    #column extraction

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]  # row kha se kha tk , column kha se kha tk

array([[ 5,  6],
       [ 9, 10]])