<h1>Array Attributes


In [4]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
a3

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])