<h1>Numpy </h1>
 library for scientific calculations and data science and ml aswell


why numpy ??
different people from different domains came together during the time when data science was developing and python was a easy to learn language and numpy is created in c so its fast .






<h3>ndArrays</h3>

<h3> all the below methods are used to create nd array and their initiallisations

In [2]:
import numpy as np

a= np.array([1,2,3,4])
print(a)
#dtype 
np.array([1,2,3],dtype=float)


[1 2 3 4]


array([1., 2., 3.])

In [3]:
#np.arange

np.arange(1,10)  #phela included dusra excluded

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#with reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
#np.ones and np.zeros

print(np.ones((3,4)))          #har item is 1 
np.ones((9))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# np.rand0m

np.random.random((3,4))

array([[0.33115793, 0.09882423, 0.30094728, 0.00795205],
       [0.27523573, 0.81346389, 0.14607135, 0.31006189],
       [0.67090368, 0.48597036, 0.88544357, 0.9221142 ]])

In [7]:
#np.linspace  -- >> linearly space 

np.linspace(-10,10,10)  #first two range and last no. of items

#equal distance pr points bnayega

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [8]:
#np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])