<h4> NUMPY array VS Python Lists

In [1]:
#speed 

#list 

a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]

c =[ ]
import time
start = time.time() 
for i in range(len(a)):
   c.append(a[i] + b[i])

print(time.time()-start)

2.1665990352630615


In [2]:
#numpy
import numpy as np 
a=np.arange(10000000)

b=np.arange(10000000,20000000)

start = time.time() 
c=a+b

print(time.time()-start)

0.19951725006103516


In [5]:
2.1665990352630615/0.19951725006103516

10.859206582890794

In [7]:
#memory 

a = [i for i in range (10000000)]
import sys 

sys.getsizeof(a)

89095160

In [8]:
a = np.arange(10000000)
sys.getsizeof(a)

80000112

convinence you have seen the above cells 

HENCE NUMPY IS FASTER AND BETTER 

<h1>Advanced indexing 

In [19]:
#normal indexing and slicing 

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
#fancy indexing 

# jb normal tarike se kaam na nikle then hum use krte  h fancy indexing 

a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a[[0,2,3,5]]  # ist k andar jo chiye usse sidhe sidhe dal  do 

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [15, 16, 17]])

In [22]:
a[: ,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
#boolean indexing 
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)

 #randint(no. kha se kha tk and kitne chiye ) . kesa shape ka arrayb chiye 
a

array([[13, 80, 33, 87],
       [30, 96, 99,  2],
       [ 7, 21, 77, 41],
       [89, 17, 68,  2],
       [81, 68, 35, 96],
       [80,  7, 76, 17]], dtype=int32)