<h3>np.sort</h3>

return a sorted copy of an array

In [1]:
#code 
import numpy as np
a= np.random.randint(1,100,15)
a

array([58, 76, 88, 81, 93,  6, 10, 59, 31, 31, 70, 29, 46, 78, 13],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)

In [ ]:
np.sort(a)

array([ 6, 10, 13, 29, 31, 31, 46, 58, 59, 70, 76, 78, 81, 88, 93],
      dtype=int32)

In [10]:
np.sort(b,axis=0)   #column wise when axis =0
np.sort(b,axis=1)   #row wise when axis is = 1 

array([[59, 72, 76, 99],
       [ 9, 40, 47, 74],
       [20, 62, 74, 84],
       [ 7, 10, 16, 77],
       [27, 39, 41, 53],
       [ 5,  8,  9, 70]], dtype=int32)

In [ ]:
np.sort(a)[::-1]  # reverse

array([93, 88, 81, 78, 76, 70, 59, 58, 46, 31, 31, 29, 13, 10,  6],
      dtype=int32)

np.append

the append appends values along the mentioned axis at the end of the array 

In [11]:
#code
np.append(a,200)  # 200 append hogya 

array([ 58,  76,  88,  81,  93,   6,  10,  59,  31,  31,  70,  29,  46,
        78,  13, 200])

In [16]:
np.append(b,np.ones((b.shape[0],1)),axis=1) 
#append( b , syntax to add column of ones ( shape to be kept ),axis)


array([[99., 72., 59., 76.,  1.],
       [74., 40.,  9., 47.,  1.],
       [84., 74., 62., 20.,  1.],
       [10., 77., 16.,  7.,  1.],
       [27., 39., 53., 41.,  1.],
       [ 9.,  8., 70.,  5.,  1.]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis .


In [17]:
#code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis = 0) # rowwise 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1) #columnwise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

with the help of np.unique method we can get the unique values from a given parameter 

In [22]:
e = np.array([1,2,1,2,3,3,4,4,5,5,6,6])

np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims



with the help of numpy.expand_dims() method , we can get the expanded dimensions of an array

In [26]:
a
a.shape

(15,)

In [27]:
np.expand_dims(a,axis=0)  #2d bna diya 

a.shape

(15,)

In [28]:
np.expand_dims(a,axis=1)  

a.shape

(15,)

np.where 



the numpy.where() function returns the indices of elements in an input array where the given condition is satisfied 

In [ ]:
a


array([58, 76, 88, 81, 93,  6, 10, 59, 31, 31, 70, 29, 46, 78, 13],
      dtype=int32)

In [ ]:
# find all the indices with value greater than 50

np.where(a>50)  #  outputs are the index positions 

(array([ 0,  1,  2,  3,  4,  7, 10, 13]),)

In [31]:
# replace all values > 50 with 0

np.where(a> 50 , 0 ,a )  
# np.where( a > 50 , jo hain unhe 0 kr do , jo nhi h unhe vese hi chor do )

array([ 0,  0,  0,  0,  0,  6, 10,  0, 31, 31,  0, 29, 46,  0, 13],
      dtype=int32)

In [34]:
np.where(a%2 == 0 , 2 ,3 )

array([2, 2, 2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 2, 3])

np.argmax

the numpy.argmax() function returns indices of the max element of the array in aparticular axis .

In [35]:
a
np.argmax(a)

np.int64(4)

In [39]:
np.argmax(b,axis=0) #column wise max
np.argmax(b,axis=1) #rowise

array([0, 0, 0, 1, 2, 2])

In [42]:
#np.argmin

np.argmin(a)


np.int64(5)

<h2> cumsum


numpy.cumsum() func is useddd when we want to compute the cumulative sum of array elements over a given axis.

In [44]:
a

array([58, 76, 88, 81, 93,  6, 10, 59, 31, 31, 70, 29, 46, 78, 13],
      dtype=int32)

In [45]:
np.cumsum(a)

array([ 58, 134, 222, 303, 396, 402, 412, 471, 502, 533, 603, 632, 678,
       756, 769])

In [46]:
b

array([[99, 72, 59, 76],
       [74, 40,  9, 47],
       [84, 74, 62, 20],
       [10, 77, 16,  7],
       [27, 39, 53, 41],
       [ 9,  8, 70,  5]], dtype=int32)

In [49]:
np.cumsum(b,axis=0) #column wise
np.cumsum(b,axis=1) #row wise

array([[ 99, 171, 230, 306],
       [ 74, 114, 123, 170],
       [ 84, 158, 220, 240],
       [ 10,  87, 103, 110],
       [ 27,  66, 119, 160],
       [  9,  17,  87,  92]])

<h3>cumprod 

cummilative product 

In [50]:
a
np.cumprod(a)

array([                  58,                 4408,               387904,
                   31420224,           2922080832,          17532484992,
               175324849920,       10344166145280,      320669150503680,
           9940743665614080,   695852056592985600,  1732965567487030784,
        5929439809565209600,  1327703303347558400, -1186601130191292416])

<h3>percentile

numpy.percentile()function used to compute the nth percentile of the given data along a specific line 

In [55]:
a

np.percentile(a,80)  #kitna chiye 100 is for 100percentile

np.float64(78.60000000000001)

In [56]:
np.median(a)

np.float64(58.0)

histogram



freq. chart 

In [57]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])  #bins == spaces

(array([1, 2, 1, 2, 1, 2, 0, 3, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [58]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))


<h3>np.corrcoef</h3>

return pearson product moment correlation coefficients.



kisi k bdlne pr kisi  dusre pr kitta frk pdega 

In [60]:
salary = np.array([20000,40000,23000,35000,60000])

experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

# phele salary ka salary k sath then experience ka and then same process for experience

array([[1.        , 0.25849551],
       [0.25849551, 1.        ]])

np.isin()


with the help of numpy isin() method , we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [61]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([10, 70], dtype=int32)

np.flip


function reverses the order of array elemts along the specified axis , preserving the shape of the array 

In [63]:
a

array([58, 76, 88, 81, 93,  6, 10, 59, 31, 31, 70, 29, 46, 78, 13],
      dtype=int32)

In [62]:
np.flip(a)

array([13, 78, 46, 29, 70, 31, 31, 59, 10,  6, 93, 81, 88, 76, 58],
      dtype=int32)

In [64]:
b

array([[99, 72, 59, 76],
       [74, 40,  9, 47],
       [84, 74, 62, 20],
       [10, 77, 16,  7],
       [27, 39, 53, 41],
       [ 9,  8, 70,  5]], dtype=int32)

In [ ]:
np.flip(b)  #columnn and row dono flip hota h 

array([[ 5, 70,  8,  9],
       [41, 53, 39, 27],
       [ 7, 16, 77, 10],
       [20, 62, 74, 84],
       [47,  9, 40, 74],
       [76, 59, 72, 99]], dtype=int32)

In [ ]:
np.flip(b,axis=0)  #only row

array([[ 9,  8, 70,  5],
       [27, 39, 53, 41],
       [10, 77, 16,  7],
       [84, 74, 62, 20],
       [74, 40,  9, 47],
       [99, 72, 59, 76]], dtype=int32)

np.put

replaces specific elements of a new array with given values of p_array.array indexed works on flattened array.

In [ ]:


np.put(a,[0,1],[110,530])  # array dalo [ kha pr changes krne h ] , [ ky changes krne  h]

# permanent changes 

In [69]:
print(a)

[110 530  88  81  93   6  10  59  31  31  70  29  46  78  13]


np.delete



returns a new array with the deletion of sub arrays along with the mentioned axis

In [71]:
np.delete(a,0)

#given index ka item delete ho jayega

array([530,  88,  81,  93,   6,  10,  59,  31,  31,  70,  29,  46,  78,
        13], dtype=int32)

In [75]:
np.delete(a,[2,0,4])

array([530,  81,   6,  10,  59,  31,  31,  70,  29,  46,  78,  13],
      dtype=int32)

SET FUNCTIONS 

np.union1d

np.intersection1d

np.setdiff1d

np.setxor1d

np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])  #union

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)  # intersection

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n) #uniques

array([1, 2])

In [79]:
np.setxor1d(m,n)  # common hta dega

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,1)  

C:\Users\goswa\AppData\Local\Temp\ipykernel_28012\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

np.clip

is used to clip (limit) the vlues in an array

In [ ]:
np.clip(a,a_min = 25 , a_max = 34)

#limiting values in a certain range 

array([34, 34, 34, 34, 34, 25, 25, 34, 31, 31, 34, 29, 34, 34, 25],
      dtype=int32)